### ISSUE TITLE
Remove "RackNES" substring from plugin name since it's redundant

### ISSUE THREAD

**Issue by AndrewBelt** [Kautenja/RackNES#28]
Since the brand string of this plugin is "KautenjaDSP" in `plugin.json`, the plugin name should probably be just that instead of "KautenjaDSP-RackNES". The plugin name is what people see on this page. https://library.vcvrack.com/KautenjaDSP-RackNES

The slug should stay the same.

**Comment by Kautenja** [comment]
This has been updated in the latest version, 1.1.5, which will release next week when a few more small issues are resolved. I have some more plugins planned down the road, would this plugin.json schema be a generally good way of approaching maintaining a single brand across the collection of plugins?

```json
{
  "slug": "KautenjaDSP-<plugin>",
  "version": "1.1.4",
  "license": "GPL-3.0-or-later",
  "name": "<plugin>",
  "brand": "KautenjaDSP",
  "author": "Christian Kauten",
 ...
}
```

**Comment by AndrewBelt** [comment]
In this plugin's case, the name should be "KautenjaDSP". If you want to add more modules, you can add them to this plugin. RackNES is a module that belongs to the "KautenjaDSP" plugin.

**Comment by Kautenja** [comment]
Hmm that doesn't really make sense to me. In my case "KautenjaDSP" is just an arbitrary abstraction of my brand to unify my (planned) multiple plugins. If I were to use KautenjaDSP as a plugin name, it would be the plugin that contains my regular musical modules. I don't want issues related to an NES emulator in that repository when it goes public, nor do I want the NES emulator code lumped in there with the actual DSP code. Ideally, RackNES would belong to some larger plugin called "Emulators" or something, but because it's the only module in the plugin right now, it seems like RackNES is the most appropriate name for now.

I'm also working on some ports of old chip emulations [here](https://github.com/Kautenja/PotatoChips) that I'd like to keep organized in their own plugin (coined "Potato Chips") for the same reasons as above. 

An final point for me against trunk repositories would be my usage of Travis CI as a build server, which will get slowed down by a trunk repository that grows infinitely with every new module I write and new dependency or library that I add.

Visually, this is how I'm mentally modeling things:

- KautenjaDSP Brand
    - RackNES Plugin (or Emulators plugin)
        - RackNES Module
        - Rack2600
    - Potato Chips Plugin
        - 2A03 Module
        - VRC6 Module
        - Namco106 Module
        - ...
    - Other Plugin
        - Module1
        - Module2
        - Module3
        - ...
    - ...

**Comment by Kautenja** [comment]
I can rename the repository and plugin here to something like "Arcade" if that makes more sense than using the module's name.

**Comment by AndrewBelt** [comment]
Oh okay, if you plan to make more plugins using that heirachy, "Kautenja RackNES" or "Kautenja Arcade" would make more sense for the plugin name. If this plugin is a singleton (contains only one module) the first option is fine. If you plan to add other modules to this plugin, the second would make more sense.

**Comment by Kautenja** [comment]
Perfect! I'll leave it as RackNES for now as it is a singleton module currently. If more modules are added, I'll change it to something like Arcade.

**Comment by AndrewBelt** [comment]
Well now it just says "RackNES". The plugin name should definitely be "KautenjaDSP [something]"

**Comment by Kautenja** [comment]
oh whoops, fixed now. The plugin is named "KautenjaDSP RackNES"
