### ISSUE TITLE
Serialize/unserialize current state and saved state to patch

### ISSUE THREAD

**Issue by AndrewBelt** [Kautenja/RackNES#4]
If you have some way of getting the RAM bytes, you can save/restore it with the following code in `dataToJson()` and `dataFromJson()`. I'd recommend base64 as an easy way to encode an arbitrary buffer.
```cpp
std::vector<uint8_t> ram;
ram.assign(ramData, ramLen);
std::string ramString = string::toBase64(ram);
...
std::vector<uint8_t> ram = string::fromBase64(ramString);
```
You could also compress it with zlib with `string:compress/uncompress`, but that's a bit more involved and probably not worth it for 2KiB RAM.

**Comment by Kautenja** [comment]
Perfect, I'll start experimenting with this.

**Comment by Kautenja** [comment]
For serialization, I'm wondering if storing the entire ROM contents in the patch file is desirable behavior. Right now I have things set up to store the path to the ROM and load the ROM data from the remote ROM file when the patch loads. This is how many of the file-based sampler modules that I've looked at work (Bidoo, for example). However, it is possible to serialize the ROM contents as well and store this in the patch file so that the patch file can move between machines with different file systems and still work as expected. This is similar to "consolidation" in Ableton Live, and is being considered in issue #13. @AndrewBelt what are your thoughts on this? The ROM files are relatively small; the largest I've seen was roughly 400KB. If moving in this direction would zlib be recommended instead of base64?

**Comment by AndrewBelt** [comment]
Absolute file path is fine. 400KB is probably too large for patch files.
